### ISSUE TITLE
测试手机客户端能不能从 workflow 项目的 bundle 直接升级到 二合一项目 的 bundle

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-project-saas#14]

**Comment by hotlong** [comment]
可以先用手机连上本地的workflow编译后的bundle，然后在同一个端口运行二合一编译后的项目，测试手机客户端能否自动升级。

**Comment by sunhaolin** [comment]
测试过程：
1、手机连上本地的workflow编译后的bundle，进入待审核页面后最小化app
2、停掉workflow，同一个端口运行saas后，打开app无升级提示，申请单仍可点开；
3、杀掉app进程后进入app待审核页面一直加载中，app无法使用
