### ISSUE TITLE
公告，新建公告，图片控件异常

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-project-saas#144]
点图片后，无法继续操作
![image](https://user-images.githubusercontent.com/7553007/79553395-ff1e1000-80ce-11ea-956f-436fa689d5b8.png)

**Comment by marchtian** [comment]
知识库中也是同样的问题

**Comment by yinlianghui** [comment]
- 代码在summernote分支，需要孙老师帮忙确认之前改的`steedos:oauth2-server`包中的express相关代码是否完全没影响才能提交，我不太懂这块
- i18n翻译这块也解决了，但是相关资源文件没有放到steedos-platform项目的i18n包中（因为是js文件），以后国际化有需求再说吧
