### ISSUE TITLE
宁波某客户想停用用户，找到所属审批岗位，删除该用户，再将该用户设为无效后，该用户所属的审批岗位里其他成员疑似也被删除了

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-project-saas#153]
该操作由客户下午2点46左右进行，下午5点左右才发现问题，不确定是不是因为程序bug造成的

**Comment by sunhaolin** [comment]
由于客户手动删除导致
原因可能为：在用户详细页面显示的岗位成员列表只显示了岗位名称和管辖范围，没显示岗位成员字段可能引起用户误会，为避免误会增加显示岗位成员
